# Generated by Django 4.0.1 on 2024-07-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='editable',
            new_name='edited',
        ),
    ]
