# Generated by Django 4.0.1 on 2024-07-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_avatart_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatart',
            new_name='avatar',
        ),
    ]
