name: Build, Test and Deploy Postagram
on:
  push:
    branches: [master] # main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Injecting env vars
      run: |
        echo "${{ secrets.TEST_SECRETS }}" >> .env
