name: Build and deploy frontend

on:
  push:
    branches: [ main ]

jobs:
  build-test_deploy:
    name: Tests
    runs-on: ubtuntu-latest
    defaults:
      run:
        working-directory: ./social-media-react
    steps:
      - uses: actions/checkout@v2

      - name: Injecting environment variables
        run: echo "REACT_APP_API_URL=${{ secrets.API_URL }}" >> .env

      - name: Installing dependencies
        run: yarn install

      - name: Running tests
        run: yarn test

      - name: Building project
        run: yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KY}}
          aws-region: us-west-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://postagram --delete
